### ISSUE TITLE
how to generate a QR code, or a target link?

### ISSUE THREAD

**Issue by liangzid** [wandercn/alipay_sdk_rust#4]
I have read your document, it seems that I can build a client based on the information of sellers, while I am not clear how the buyer provides its information. In codes:
```rust
    let out_trade_no = gostd::time::Now().UnixNano().to_string();
    let mut biz_content = biz::TradeCreateBiz::new();
    biz_content.set_subject("huawei Mate50");
    biz_content.set_out_trade_no(&out_trade_no); // "1620630871769533112"
    biz_content.set_total_amount("5");
    biz_content.set("seller_id", "2088621955702975");
    biz_content.set_buyer_id("2088102175953034");
    biz_content.set("Timestamp", "2022-07-11 16:09:04");/////!
    let client = new_pay_client()?;
    let res = client.trade_create(&biz_content)?;
```
how do I get biz_content. Thanks.

**Comment by wandercn** [comment]
read docs https://docs.rs/alipay_sdk_rust/1.0.4/alipay_sdk_rust/pay/struct.PayClient.html
fn trade_precreate() for qrcode
fn trade_app_pay  for app 
fn trade_wap_pay() for wap
fn trade_page_pay() for web 
这些应该是你需要的东西，希望对你有帮助。具体需要哪些字段看文档的官方文档，我程序里写的必要字段，其他可选字段
你看https://docs.rs/alipay_sdk_rust/1.0.4/alipay_sdk_rust/biz/trait.BizContenter.html
有个fn set(),可选字段你可以自己添加进去，可以添加哪些参考 https://opendocs.alipay.com/apis/api_1/alipay.trade.precreate 官方文档字段说明

**Comment by wandercn** [comment]
biz 必须字段已经在对应的方法，可以看https://docs.rs/alipay_sdk_rust/1.0.4/alipay_sdk_rust/biz/index.html
TradePrecreateBiz <--> fn trade_precreate() 
TradeWapPayBiz <--> fn trade_wap_pay()

**Comment by liangzid** [comment]
奥奥奥，感谢！
